"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.cashRegisterRouter = void 0;
const express_1 = require("express");
const CashRegisterController_1 = require("../../controller/CashRegisterController");
const authMiddleware_1 = require("../../infrastructure/security/authMiddleware");
const rbacMiddleware_1 = require("../../infrastructure/security/rbacMiddleware");
exports.cashRegisterRouter = (0, express_1.Router)();
exports.cashRegisterRouter.get('/cash-registers', CashRegisterController_1.getCashRegisters);
exports.cashRegisterRouter.get('/cash-registers/active', CashRegisterController_1.getActiveCashRegisters);
exports.cashRegisterRouter.get('/cash-registers/number/:number', CashRegisterController_1.getCashRegisterByNumber);
exports.cashRegisterRouter.get('/cash-registers/:id', CashRegisterController_1.getCashRegisterById);
exports.cashRegisterRouter.post('/cash-registers', CashRegisterController_1.saveCashRegister);
exports.cashRegisterRouter.put('/cash-registers/:id', CashRegisterController_1.updateCashRegister);
exports.cashRegisterRouter.delete('/cash-registers/:id', authMiddleware_1.verifyToken, (0, rbacMiddleware_1.authorize)(['cajero', 'admin']), CashRegisterController_1.deleteCashRegister);
