"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.consumableTypeRouter = void 0;
const express_1 = require("express");
const ConsumableTypeController_1 = require("../../controller/ConsumableTypeController");
const authMiddleware_1 = require("../../infrastructure/security/authMiddleware");
const rbacMiddleware_1 = require("../../infrastructure/security/rbacMiddleware");
exports.consumableTypeRouter = (0, express_1.Router)();
exports.consumableTypeRouter.get("/consumable-type", ConsumableTypeController_1.getConsumableTypes);
exports.consumableTypeRouter.get("/consumable-type/:id", ConsumableTypeController_1.getConsumableTypeById);
exports.consumableTypeRouter.post("/consumable-type", ConsumableTypeController_1.saveConsumableType);
exports.consumableTypeRouter.put("/consumable-type/:id", ConsumableTypeController_1.updateConsumableType);
exports.consumableTypeRouter.delete("/consumable-type/:id", authMiddleware_1.verifyToken, (0, rbacMiddleware_1.authorize)(["all"]), ConsumableTypeController_1.deleteConsumableType);
