"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.consumableRouter = void 0;
const express_1 = require("express");
const ConsumableController_1 = require("../../controller/ConsumableController");
const rbacMiddleware_1 = require("../../infrastructure/security/rbacMiddleware");
const authMiddleware_1 = require("../../infrastructure/security/authMiddleware");
exports.consumableRouter = (0, express_1.Router)();
exports.consumableRouter.get("/consumable", ConsumableController_1.getConsumables);
exports.consumableRouter.get("/consumable/supplier/:supplierId", ConsumableController_1.getConsumablesBySupplier);
exports.consumableRouter.get("/consumable/:id", ConsumableController_1.getConsumableById);
exports.consumableRouter.post("/consumable", ConsumableController_1.saveConsumable);
exports.consumableRouter.put("/consumable/:id", ConsumableController_1.updateConsumable);
exports.consumableRouter.delete("/consumable/:id", authMiddleware_1.verifyToken, (0, rbacMiddleware_1.authorize)(["all"]), ConsumableController_1.deleteConsumable);
