"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.ingredientRouter = void 0;
const express_1 = require("express");
const IngredientController_1 = require("../../controller/IngredientController");
const authMiddleware_1 = require("../../infrastructure/security/authMiddleware");
const rbacMiddleware_1 = require("../../infrastructure/security/rbacMiddleware");
exports.ingredientRouter = (0, express_1.Router)();
exports.ingredientRouter.get("/ingredient", IngredientController_1.getIngredients);
exports.ingredientRouter.get("/ingredient/product/:productId", IngredientController_1.getIngredientsByProduct);
exports.ingredientRouter.get("/ingredient/:id", IngredientController_1.getIngredientById);
exports.ingredientRouter.post("/ingredient", IngredientController_1.saveIngredient);
exports.ingredientRouter.put("/ingredient/:id", IngredientController_1.updateIngredient);
exports.ingredientRouter.delete("/ingredient/:id", authMiddleware_1.verifyToken, (0, rbacMiddleware_1.authorize)(["all"]), IngredientController_1.deleteIngredient);
