"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.productRouter = void 0;
const express_1 = require("express");
const ProductController_1 = require("../../controller/ProductController");
const authMiddleware_1 = require("../../infrastructure/security/authMiddleware");
const rbacMiddleware_1 = require("../../infrastructure/security/rbacMiddleware");
exports.productRouter = (0, express_1.Router)();
exports.productRouter.get("/products", ProductController_1.getProducts);
exports.productRouter.get("/products/active", ProductController_1.getActiveProducts);
exports.productRouter.get("/products/:id", ProductController_1.getProductById);
exports.productRouter.post("/products", ProductController_1.saveProduct);
exports.productRouter.put("/products/:id", ProductController_1.updateProduct);
exports.productRouter.delete("/products/:id", authMiddleware_1.verifyToken, (0, rbacMiddleware_1.authorize)(["all"]), ProductController_1.deleteProduct);
