"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.purchaseRouter = void 0;
const express_1 = require("express");
const PurchaseController_1 = require("../../controller/PurchaseController");
const authMiddleware_1 = require("../../infrastructure/security/authMiddleware");
const rbacMiddleware_1 = require("../../infrastructure/security/rbacMiddleware");
exports.purchaseRouter = (0, express_1.Router)();
exports.purchaseRouter.get("/purchases", PurchaseController_1.getPurchases);
exports.purchaseRouter.get("/purchases/supplier/:supplierId", PurchaseController_1.getPurchasesBySupplier);
exports.purchaseRouter.get("/purchases/:id", PurchaseController_1.getPurchaseById);
exports.purchaseRouter.post("/purchases", PurchaseController_1.createPurchase);
exports.purchaseRouter.put("/purchases/:id", PurchaseController_1.updatePurchase);
exports.purchaseRouter.delete("/purchases/:id", authMiddleware_1.verifyToken, (0, rbacMiddleware_1.authorize)(["admin"]), PurchaseController_1.deletePurchase);
